#############################################################################
# Makefile for building: serpDesktop
# Generated by qmake (3.0) (Qt 5.2.0)
# Project:  serpDesktop.pro
# Template: app
# Command: /home/derek/Qt/5.2.0/gcc_64/bin/qmake -spec linux-g++ -o Makefile serpDesktop.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WEBKITWIDGETS_LIB -DQT_QUICK_LIB -DQT_POSITIONING_LIB -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_WEBKIT_LIB -DQT_QML_LIB -DQT_WIDGETS_LIB -DQT_NETWORK_LIB -DQT_SENSORS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../../Qt/5.2.0/gcc_64/mkspecs/linux-g++ -I. -I../../Qt/5.2.0/gcc_64/include -I../../Qt/5.2.0/gcc_64/include/QtWebKitWidgets -I../../Qt/5.2.0/gcc_64/include/QtQuick -I../../Qt/5.2.0/gcc_64/include/QtPositioning -I../../Qt/5.2.0/gcc_64/include/QtOpenGL -I../../Qt/5.2.0/gcc_64/include/QtPrintSupport -I../../Qt/5.2.0/gcc_64/include/QtWebKit -I../../Qt/5.2.0/gcc_64/include/QtQml -I../../Qt/5.2.0/gcc_64/include/QtWidgets -I../../Qt/5.2.0/gcc_64/include/QtNetwork -I../../Qt/5.2.0/gcc_64/include/QtSensors -I../../Qt/5.2.0/gcc_64/include/QtGui -I../../Qt/5.2.0/gcc_64/include/QtCore -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/derek/Qt/5.2.0/gcc_64 -Wl,-rpath,/home/derek/Qt/5.2.0/gcc_64/lib -Wl,-rpath-link,/home/derek/Qt/5.2.0/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/derek/Qt/5.2.0/gcc_64/lib -lQt5WebKitWidgets -lX11 -lxslt -lgio-2.0 -lgstapp-0.10 -lgstinterfaces-0.10 -lgstpbutils-0.10 -pthread -lgstvideo-0.10 -lgstbase-0.10 -lgstreamer-0.10 -lgobject-2.0 -lgmodule-2.0 -lxml2 -lgthread-2.0 -lrt -lglib-2.0 -lQt5Sql -lQt5Quick -lQt5Positioning -lQt5OpenGL -lQt5PrintSupport -lQt5WebKit -lQt5Qml -lQt5Widgets -lQt5Network -lQt5Sensors -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/derek/Qt/5.2.0/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp qrc_serp.cpp \
		moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		qrc_serp.o \
		moc_mainwindow.o
DIST          = ../../Qt/5.2.0/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/common/shell-unix.conf \
		../../Qt/5.2.0/gcc_64/mkspecs/common/unix.conf \
		../../Qt/5.2.0/gcc_64/mkspecs/common/linux.conf \
		../../Qt/5.2.0/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.2.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt/5.2.0/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt/5.2.0/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt/5.2.0/gcc_64/mkspecs/qconfig.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/spec_post.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/default_post.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/qt.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/resources.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/moc.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/uic.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/yacc.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/lex.prf \
		serpDesktop.pro \
		serp.qrc \
		serpDesktop.pro
QMAKE_TARGET  = serpDesktop
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = serpDesktop


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: serpDesktop.pro ../../Qt/5.2.0/gcc_64/mkspecs/linux-g++/qmake.conf ../../Qt/5.2.0/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/common/shell-unix.conf \
		../../Qt/5.2.0/gcc_64/mkspecs/common/unix.conf \
		../../Qt/5.2.0/gcc_64/mkspecs/common/linux.conf \
		../../Qt/5.2.0/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.2.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt/5.2.0/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt/5.2.0/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt/5.2.0/gcc_64/mkspecs/qconfig.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.2.0/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/spec_post.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/default_post.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/qt.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/resources.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/moc.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/uic.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/yacc.prf \
		../../Qt/5.2.0/gcc_64/mkspecs/features/lex.prf \
		serpDesktop.pro \
		serp.qrc \
		/home/derek/Qt/5.2.0/gcc_64/lib/libQt5WebKitWidgets.prl \
		/home/derek/Qt/5.2.0/gcc_64/lib/libQt5Quick.prl \
		/home/derek/Qt/5.2.0/gcc_64/lib/libQt5Qml.prl \
		/home/derek/Qt/5.2.0/gcc_64/lib/libQt5Network.prl \
		/home/derek/Qt/5.2.0/gcc_64/lib/libQt5Core.prl \
		/home/derek/Qt/5.2.0/gcc_64/lib/libQt5Gui.prl \
		/home/derek/Qt/5.2.0/gcc_64/lib/libQt5Positioning.prl \
		/home/derek/Qt/5.2.0/gcc_64/lib/libQt5OpenGL.prl \
		/home/derek/Qt/5.2.0/gcc_64/lib/libQt5Widgets.prl \
		/home/derek/Qt/5.2.0/gcc_64/lib/libQt5PrintSupport.prl \
		/home/derek/Qt/5.2.0/gcc_64/lib/libQt5WebKit.prl \
		/home/derek/Qt/5.2.0/gcc_64/lib/libQt5Sql.prl \
		/home/derek/Qt/5.2.0/gcc_64/lib/libQt5Sensors.prl
	$(QMAKE) -spec linux-g++ -o Makefile serpDesktop.pro
../../Qt/5.2.0/gcc_64/mkspecs/features/spec_pre.prf:
../../Qt/5.2.0/gcc_64/mkspecs/common/shell-unix.conf:
../../Qt/5.2.0/gcc_64/mkspecs/common/unix.conf:
../../Qt/5.2.0/gcc_64/mkspecs/common/linux.conf:
../../Qt/5.2.0/gcc_64/mkspecs/common/gcc-base.conf:
../../Qt/5.2.0/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../Qt/5.2.0/gcc_64/mkspecs/common/g++-base.conf:
../../Qt/5.2.0/gcc_64/mkspecs/common/g++-unix.conf:
../../Qt/5.2.0/gcc_64/mkspecs/qconfig.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.2.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.2.0/gcc_64/mkspecs/features/qt_functions.prf:
../../Qt/5.2.0/gcc_64/mkspecs/features/qt_config.prf:
../../Qt/5.2.0/gcc_64/mkspecs/linux-g++/qmake.conf:
../../Qt/5.2.0/gcc_64/mkspecs/features/spec_post.prf:
../../Qt/5.2.0/gcc_64/mkspecs/features/exclusive_builds.prf:
../../Qt/5.2.0/gcc_64/mkspecs/features/default_pre.prf:
../../Qt/5.2.0/gcc_64/mkspecs/features/resolve_config.prf:
../../Qt/5.2.0/gcc_64/mkspecs/features/default_post.prf:
../../Qt/5.2.0/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf:
../../Qt/5.2.0/gcc_64/mkspecs/features/warn_on.prf:
../../Qt/5.2.0/gcc_64/mkspecs/features/qt.prf:
../../Qt/5.2.0/gcc_64/mkspecs/features/resources.prf:
../../Qt/5.2.0/gcc_64/mkspecs/features/moc.prf:
../../Qt/5.2.0/gcc_64/mkspecs/features/unix/opengl.prf:
../../Qt/5.2.0/gcc_64/mkspecs/features/uic.prf:
../../Qt/5.2.0/gcc_64/mkspecs/features/unix/thread.prf:
../../Qt/5.2.0/gcc_64/mkspecs/features/testcase_targets.prf:
../../Qt/5.2.0/gcc_64/mkspecs/features/exceptions.prf:
../../Qt/5.2.0/gcc_64/mkspecs/features/yacc.prf:
../../Qt/5.2.0/gcc_64/mkspecs/features/lex.prf:
serpDesktop.pro:
serp.qrc:
/home/derek/Qt/5.2.0/gcc_64/lib/libQt5WebKitWidgets.prl:
/home/derek/Qt/5.2.0/gcc_64/lib/libQt5Quick.prl:
/home/derek/Qt/5.2.0/gcc_64/lib/libQt5Qml.prl:
/home/derek/Qt/5.2.0/gcc_64/lib/libQt5Network.prl:
/home/derek/Qt/5.2.0/gcc_64/lib/libQt5Core.prl:
/home/derek/Qt/5.2.0/gcc_64/lib/libQt5Gui.prl:
/home/derek/Qt/5.2.0/gcc_64/lib/libQt5Positioning.prl:
/home/derek/Qt/5.2.0/gcc_64/lib/libQt5OpenGL.prl:
/home/derek/Qt/5.2.0/gcc_64/lib/libQt5Widgets.prl:
/home/derek/Qt/5.2.0/gcc_64/lib/libQt5PrintSupport.prl:
/home/derek/Qt/5.2.0/gcc_64/lib/libQt5WebKit.prl:
/home/derek/Qt/5.2.0/gcc_64/lib/libQt5Sql.prl:
/home/derek/Qt/5.2.0/gcc_64/lib/libQt5Sensors.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ -o Makefile serpDesktop.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/serpDesktop1.0.0 || mkdir -p .tmp/serpDesktop1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/serpDesktop1.0.0/ && $(COPY_FILE) --parents serp.qrc .tmp/serpDesktop1.0.0/ && $(COPY_FILE) --parents mainwindow.h .tmp/serpDesktop1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp .tmp/serpDesktop1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/serpDesktop1.0.0/ && (cd `dirname .tmp/serpDesktop1.0.0` && $(TAR) serpDesktop1.0.0.tar serpDesktop1.0.0 && $(COMPRESS) serpDesktop1.0.0.tar) && $(MOVE) `dirname .tmp/serpDesktop1.0.0`/serpDesktop1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/serpDesktop1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_serp.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_serp.cpp
qrc_serp.cpp: serp.qrc \
		web/index.html \
		web/img/glyphicons-halflings-white.png \
		web/img/derek.jpeg \
		web/img/bg01.png \
		web/img/glyphicons-halflings.png \
		web/fonts/fontawesome-webfont.ttf \
		web/fonts/fontawesome-webfont.svg \
		web/fonts/FontAwesome.otf \
		web/fonts/fontawesome-webfont.woff \
		web/fonts/fontawesome-webfont.eot \
		web/css/bootstrap-switch.css \
		web/css/main.css \
		web/css/enyo.css \
		web/css/animate.min.css \
		web/css/bootstrap.min.css \
		web/css/font-awesome.css \
		web/css/bootstrap-responsive.min.css \
		web/css/font-awesome.min.css \
		web/js/sweetAPI.js \
		web/js/main.js \
		web/js/sweetGUI.js \
		web/js/store.min.js \
		web/js/init.js \
		web/js/jquery.min.js \
		web/js/offline.min.js \
		web/js/bootstrap.min.js \
		web/js/enyostuff.js \
		web/js/sweetApps.js \
		web/js/bootstrap-switch.min.js \
		web/js/app.js \
		web/js/enyo.js \
		web/js/modernizr-2.6.2-respond-1.1.0.min.js
	/home/derek/Qt/5.2.0/gcc_64/bin/rcc -name serp serp.qrc -o qrc_serp.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: ../../Qt/5.2.0/gcc_64/include/QtWidgets/QMainWindow \
		../../Qt/5.2.0/gcc_64/include/QtWidgets/qmainwindow.h \
		../../Qt/5.2.0/gcc_64/include/QtWidgets/qwidget.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qwindowdefs.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qglobal.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qconfig.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qfeatures.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_integrity.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_power.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_alpha.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_bfin.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_mips.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_s390.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_sparc.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_x86.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_unix.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qmutex.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qlogging.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qflags.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qnamespace.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qobject.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qstring.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qchar.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qbytearray.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qrefcount.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qarraydata.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qlist.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qiterator.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qmetatype.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qisenum.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qmargins.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qrect.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qsize.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qpoint.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qpaintdevice.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qpalette.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qcolor.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qrgb.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qstringlist.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qdatastream.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qiodevice.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qpair.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qregexp.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qbrush.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qvector.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qmatrix.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qpolygon.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qregion.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qline.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qtransform.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qpainterpath.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qimage.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qpixmap.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qshareddata.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qhash.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qfont.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qfontmetrics.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qfontinfo.h \
		../../Qt/5.2.0/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qcursor.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qkeysequence.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qevent.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qvariant.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qmap.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qdebug.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qtextstream.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qlocale.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qset.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qurl.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qurlquery.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qfile.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qfiledevice.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qvector2d.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qtouchdevice.h \
		../../Qt/5.2.0/gcc_64/include/QtWidgets/qtabwidget.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qicon.h \
		mainwindow.h
	/home/derek/Qt/5.2.0/gcc_64/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		../../Qt/5.2.0/gcc_64/include/QtWebKitWidgets/QWebView
	/home/derek/Qt/5.2.0/gcc_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../Qt/5.2.0/gcc_64/include/QtWidgets/QMainWindow \
		../../Qt/5.2.0/gcc_64/include/QtWidgets/qmainwindow.h \
		../../Qt/5.2.0/gcc_64/include/QtWidgets/qwidget.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qwindowdefs.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qglobal.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qconfig.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qfeatures.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_integrity.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_power.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_alpha.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_bfin.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_mips.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_s390.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_sparc.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_x86.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_unix.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qmutex.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qlogging.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qflags.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qnamespace.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qobject.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qstring.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qchar.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qbytearray.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qrefcount.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qarraydata.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qlist.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qiterator.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qmetatype.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qisenum.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qmargins.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qrect.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qsize.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qpoint.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qpaintdevice.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qpalette.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qcolor.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qrgb.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qstringlist.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qdatastream.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qiodevice.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qpair.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qregexp.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qbrush.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qvector.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qmatrix.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qpolygon.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qregion.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qline.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qtransform.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qpainterpath.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qimage.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qpixmap.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qshareddata.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qhash.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qfont.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qfontmetrics.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qfontinfo.h \
		../../Qt/5.2.0/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qcursor.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qkeysequence.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qevent.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qvariant.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qmap.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qdebug.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qtextstream.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qlocale.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qset.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qurl.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qurlquery.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qfile.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qfiledevice.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qvector2d.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qtouchdevice.h \
		../../Qt/5.2.0/gcc_64/include/QtWidgets/qtabwidget.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qicon.h \
		../../Qt/5.2.0/gcc_64/include/QtWidgets/QApplication \
		../../Qt/5.2.0/gcc_64/include/QtWidgets/qapplication.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qcoreapplication.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qeventloop.h \
		../../Qt/5.2.0/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qguiapplication.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../Qt/5.2.0/gcc_64/include/QtWidgets/QMainWindow \
		../../Qt/5.2.0/gcc_64/include/QtWidgets/qmainwindow.h \
		../../Qt/5.2.0/gcc_64/include/QtWidgets/qwidget.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qwindowdefs.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qglobal.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qconfig.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qfeatures.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_integrity.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_power.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_alpha.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_bfin.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_mips.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_s390.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_sparc.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_x86.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qatomic_unix.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qmutex.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qlogging.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qflags.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qnamespace.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qobject.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qstring.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qchar.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qbytearray.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qrefcount.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qarraydata.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qlist.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qiterator.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qmetatype.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qisenum.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qmargins.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qrect.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qsize.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qpoint.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qpaintdevice.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qpalette.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qcolor.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qrgb.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qstringlist.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qdatastream.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qiodevice.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qpair.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qregexp.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qbrush.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qvector.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qmatrix.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qpolygon.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qregion.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qline.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qtransform.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qpainterpath.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qimage.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qpixmap.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qshareddata.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qhash.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qfont.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qfontmetrics.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qfontinfo.h \
		../../Qt/5.2.0/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qcursor.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qkeysequence.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qevent.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qvariant.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qmap.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qdebug.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qtextstream.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qlocale.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qset.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qurl.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qurlquery.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qfile.h \
		../../Qt/5.2.0/gcc_64/include/QtCore/qfiledevice.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qvector2d.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qtouchdevice.h \
		../../Qt/5.2.0/gcc_64/include/QtWidgets/qtabwidget.h \
		../../Qt/5.2.0/gcc_64/include/QtGui/qicon.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

qrc_serp.o: qrc_serp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_serp.o qrc_serp.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

